
[project]
id = "vwnoznuznmrdaumjyctg"

[functions.activate-lawyer-account]
verify_jwt = false

[functions.send-lawyer-approval-email]
verify_jwt = false

[functions.crear-sesion-checkout]
verify_jwt = false

[functions.manejar-pago-exitoso]
verify_jwt = false

[functions.add-manual-case]
verify_jwt = false
