
project_id = "607ccb44-1665-499f-913d-405f57497fe5"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv4"
port = 54323
max_header_length = 4096

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
api_port = 54325
smtp_port = 54326

[storage]
enabled = true
port = 54321
file_size_limit = "50MiB"
image_transformation = true

[auth]
enabled = true
port = 54321
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_manual_linking = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.sms]
enable_signup = false
enable_confirmations = false
template = "Your code is {{ .Code }}"

[edge_runtime]
enabled = true
port = 54321

[analytics]
enabled = false
port = 54327
vector_port = 54328
backend = "postgres"

[functions.create-one-time-payment]
verify_jwt = true

[functions.create-subscription]
verify_jwt = true
