
[project]
id = "vwnoznuznmrdaumjyctg"

[functions.activate-lawyer-account]
verify_jwt = false

[functions.send-lawyer-approval-email]
verify_jwt = false

[functions.crear-sesion-checkout]
verify_jwt = true

[functions.crear-cobro]
verify_jwt = true

[functions.add-manual-case]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.pagar-cobro]
verify_jwt = true

[functions.send-whatsapp]
verify_jwt = true
