
[project]
id = "vwnoznuznmrdaumjyctg"

[functions.activate-lawyer-account]
verify_jwt = false

[functions.send-lawyer-approval-email]
verify_jwt = false

[functions.crear-sesion-checkout]
verify_jwt = true

[functions.crear-cobro]
verify_jwt = true

[functions.add-manual-case]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.pagar-cobro]
verify_jwt = true

[functions.send-whatsapp]
verify_jwt = true

[functions.password-reset-security]
verify_jwt = false

[auth.email.template.recovery]
subject = "Restablecer contraseña - KlamAI Legal"
content_path = "./supabase/email-templates/reset-password.html"

[auth.email.template.confirmation]
subject = "Confirma tu cuenta en KlamAI"
content_path = "./supabase/email-templates/confirmation.html"
