// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vwnoznuznmrdaumjyctg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3bm96bnV6bm1yZGF1bWp5Y3RnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NTA2MzEsImV4cCI6MjA2NDQyNjYzMX0.DjW-_UqsNDp23rdfTS3jXftx75o_dt67hfPBxG0kldc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);